###

GET http://localhost:6969/book
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWJlNjBlZjJkNDY0MGZiZGZjZTY5NjUiLCJpYXQiOjE3MDcxMzA2OTIsImV4cCI6MTcwNzEzNDI5Mn0.AUOvc9ju8Q7gOKPEj_Vu8I9XyM6_A3UMbhxfKA_TlRk
###
GET http://localhost:6969/book?name=book1


###

GET http://localhost:6969/user/ownBooks/65be60ef2d4640fbdfce6965
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWJlNjBlZjJkNDY0MGZiZGZjZTY5NjUiLCJpYXQiOjE3MDcxMzQxODIsImV4cCI6MTcwNzEzNzc4Mn0.vehRAWNCrXagcPfUxtyuDhFmSVGk6kJuKHVgjNuWPQU

###

POST http://localhost:6969/book
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWEyNGU5M2UyODlkNTViZWUzZTExMjQiLCJpYXQiOjE3MDUzMTI4NDksImV4cCI6MTcwNTMxNjQ0OX0.JqQE_dt0ZmbjOUrBR3l_7Sb7sauHCAHiWVUFc3TV7zI
Content-Type: application/json 

{
    "name": "try add book rest",
    "year": 2020,
    "image": "image1",
    "pages": 100,
    "price": 100,
    "rating": 5,
    "author": "65a24e93e289d55bee3e1124",
    "category": "category1",
    "summary": "summary1",
}

###

POST http://localhost:6969/book/updateOwnBook/65be60ef2d4640fbdfce6965
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWJlNjBlZjJkNDY0MGZiZGZjZTY5NjUiLCJpYXQiOjE3MDcyMTgyNDAsImV4cCI6MTcwNzIyMTg0MH0.4exd1WzL9Y8ynPDxhZKiYcrethuaBRyERclKRhv7rPw
Content-Type: application/json

{
  "name": "change"
}

# ###

# PUT http://localhost:6969/book/1234567890
# Content-Type: application/json

# {
#     "name": "book 1",
#     "_id": "1234567890"
# }

###

# POST http://localhost:6969/auth/register
# Content-Type: application/json

# {
#     "email": "test2@test.com",
#     "password": "123456789"
# }

# ###

POST http://localhost:6969/auth/login
Content-Type: application/json

{
    "email": "ori@gmail.com",
    "password": "123"
}


### 
POST http://localhost:6969/auth/register
Content-Type: application/json

{
    "name": "chen",
    "email": "chen@gmail.com",
    "password": "1234",
    "role": "author",
    "books": ["65be6059f98ce2d590f646c0" , "65be6059f98ce2d590f646c1" ,"65be6059f98ce2d590f646c2" ]
}







# ###

# POST http://localhost:6969/auth/login
# Content-Type: application/json

# {
#     "email": "testUser@test.com",
#     "password": "123456789"
# }


###
GET http://localhost:6969/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTk5MTdiMWRjMGRhMGQxZTUyYTAzNzIiLCJpYXQiOjE3MDQ1MzIwODMsImV4cCI6MTcwNDUzMjA4Nn0.-Bfn-t5KYY3rL6FKFfADuq6j1-Tb6iJcrFsbYBJW2eg


