###

GET http://localhost:6969/book
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTk0MmEyZjA3YmMwOWY4MjVmM2Q5NjUiLCJpYXQiOjE3MDQyMjY3NTgsImV4cCI6MTcwNDIzMDM1OH0.YaIODr9eNcuPAhia7aPp7Yq5V05PnUhe27HOdO8CDZc

###

GET http://localhost:6969/book?name=book1


###

GET http://localhost:6969/book/658c6bbe41cb64ee84d31465


###

POST http://localhost:6969/book
Content-Type: application/json

{
    "name": "book 1",
    "_id": "1234567891"
}

# ###

# PUT http://localhost:6969/book/1234567890
# Content-Type: application/json

# {
#     "name": "book 1",
#     "_id": "1234567890"
# }

###

# POST http://localhost:6969/auth/register
# Content-Type: application/json

# {
#     "email": "test2@test.com",
#     "password": "123456789"
# }

# ###

POST http://localhost:6969/auth/login
Content-Type: application/json

{
    "email": "testUser@test.com",
    "password": "123456789"
}

# ###

# POST http://localhost:6969/auth/login
# Content-Type: application/json

# {
#     "email": "testUser@test.com",
#     "password": "123456789"
# }